### ISSUE TITLE
License of the source code

### ISSUE THREAD

**Issue by Trilarion** [dpt/The-Great-Escape-in-C#9]
Hi,

The headers of the source file say "It is free software provided without warranty in the interests of education and software preservation.". I'm not sure what this exactly would mean.

- Is it compatible with the MIT or GPL license?
- How did the translation took place? There is a [conversion document](https://github.com/dpt/The-Great-Escape-in-C/blob/master/CONVERSION.md) but I'm not sure if all the code was just recreated or if it's more like a disassembly? If it was more like a disassembly, can it become free software? Did the original authors maybe give their consent?

Kind regards

**Comment by dpt** [comment]
Hi Trilarion,

There's no license on the project since I'm unable to offer any guarantees in that regard.

The code was disassembled from an image of the original game in [this project here](https://github.com/dpt/The-Great-Escape) then converted to C.

It was abandonware for most of the time I was actively working on it, then in 2018 it appeared for sale [on Steam](https://store.steampowered.com/app/814570/The_Great_Escape) indicating that someone has acquired those rights. However, that conflicts with some of the information I received from the game's author.

I wrote something about it [over here](http://www.davespace.co.uk/the.great.escape/legals.html).

Regards,
Dave
